CREATE PROCEDURE ALARM_PIVOT_UPDATE(IN aDate DATE, IN installation INT)
BEGIN

delete from ALARM_PIVOT where ALARM_DATE = aDate
and ID_INSTALLATION = installation;

insert into ALARM_PIVOT (ID_INSTALLATION,ID_ALARM_TYPE,ALARM_COUNT,ALARM_DATE) 
	select  ID_INSTALLATION, ID_ALARM_TYPE,  count(ID), ALARM_DATE
		from ALARM_DATA
		where ALARM_DATE = aDate
		and ID_INSTALLATION = installation
		GROUP BY (ID_ALARM_TYPE) ;

END
