CREATE DEFINER=`user`@`%` PROCEDURE `LOAD_FROM_STAGING`()
BEGIN

UPDATE ALARM_STAGING A, ALARM_TYPE T 
SET A.ID_ALARM_TYPE = T.ID, A.ALREADY_EXISTS = 1
WHERE
    A.ID_INSTALLATION = T.ID_INSTALLATION
        AND A.SYSTEM = T.SYSTEM
        AND A.SUBSYSTEM = T.SUBSYSTEM
        AND A.MESSAGE_TYPE = T.MESSAGE_TYPE
        AND A.ALARM_PRIORITY = T.ALARM_PRIORITY
        AND A.TAG_NAME = T.TAG_NAME
        AND A.DESCRIPTION = T.DESCRIPTION;

-- insert the missing alarm types    
    
INSERT INTO ALARM_TYPE (ID_INSTALLATION, SYSTEM, SUBSYSTEM, MESSAGE_TYPE, ALARM_PRIORITY, TAG_NAME, DESCRIPTION)
	SELECT  distinct ID_INSTALLATION, SYSTEM, SUBSYSTEM, MESSAGE_TYPE, ALARM_PRIORITY, TAG_NAME, DESCRIPTION  from ALARM_STAGING WHERE ALREADY_EXISTS=0;
   
-- set the alarm type id for all the staged alarms with new alarm_types
   
UPDATE ALARM_STAGING A, ALARM_TYPE T 
SET A.ID_ALARM_TYPE = T.ID, A.ALREADY_EXISTS = 1
WHERE
    A.ID_INSTALLATION = T.ID_INSTALLATION
        AND A.SYSTEM = T.SYSTEM
        AND A.SUBSYSTEM = T.SUBSYSTEM
        AND A.MESSAGE_TYPE = T.MESSAGE_TYPE
        AND A.ALARM_PRIORITY = T.ALARM_PRIORITY
        AND A.TAG_NAME = T.TAG_NAME
        AND A.DESCRIPTION = T.DESCRIPTION;

-- move the staged data to the usage table

INSERT INTO ALARM_DATA (ID_INSTALLATION, ID_ALARM_FILE, ID_ALARM_TYPE, ALARM_STATUS, ALARM_TIME, ALARM_DATE)
	SELECT ID_INSTALLATION, ID_ALARM_FILE, ID_ALARM_TYPE, ALARM_STATUS, ALARM_TIME, cast(ALARM_TIME as DATE) FROM ALARM_STAGING WHERE ALREADY_EXISTS=1 order by ALARM_TIME;

-- clear the staging area

DELETE FROM ALARM_STAGING; 
END
-- CALL `a6alarms`.`load_from_staging`();
