 drop table if exists TEMP_TABLE;
 
CREATE TABLE TEMP_TABLE (
    ID_INSTALLATION int,
    NNAME VARCHAR(64),
    ALREADY_EXISTS INT DEFAULT 0
);
       
       
-- SYSTEM --------------------------------------------

INSERT INTO TEMP_TABLE SELECT distinct ID_INSTALLATION, SYSTEM, 0 from ALARMLOAD;

UPDATE TEMP_TABLE T, SYSTEM S
SET T.ALREADY_EXISTS=1  
where 
	T.ID_INSTALLATION = S.ID_INSTALLATION 
	and t.NNAME = S.NNAME;

delete from TEMP_TABLE where ALREADY_EXISTS<>0;

INSERT INTO SYSTEM (ID_INSTALLATION, NNAME, DESCRIPTION) SELECT T.ID_INSTALLATION, T.NNAME, ""
	FROM TEMP_TABLE T;


delete from TEMP_TABLE;

-- SUBSYSTEM --------------------------------------------

INSERT INTO TEMP_TABLE SELECT distinct ID_INSTALLATION, SUBSYSTEM, 0 from ALARMLOAD;
UPDATE TEMP_TABLE T, SUBSYSTEM S
SET T.ALREADY_EXISTS=1  
where 
	T.ID_INSTALLATION = S.ID_INSTALLATION 
	and t.NNAME = S.NNAME;

delete from TEMP_TABLE where ALREADY_EXISTS<>0;

INSERT INTO SUBSYSTEM (ID_INSTALLATION, NNAME, DESCRIPTION) SELECT T.ID_INSTALLATION, T.NNAME, ""
	FROM TEMP_TABLE T;


delete from TEMP_TABLE;

-- MESSAGETYPE --------------------------------------------

INSERT INTO TEMP_TABLE SELECT distinct ID_INSTALLATION, MESSAGETYPE, 0 from ALARMLOAD;
UPDATE TEMP_TABLE T, MESSAGETYPE S
SET T.ALREADY_EXISTS=1  
where 
	T.ID_INSTALLATION = S.ID_INSTALLATION 
	and t.NNAME = S.NNAME;

delete from TEMP_TABLE where ALREADY_EXISTS<>0;

INSERT INTO MESSAGETYPE (ID_INSTALLATION, NNAME, DESCRIPTION) SELECT T.ID_INSTALLATION, T.NNAME, ""
	FROM TEMP_TABLE T;

delete from TEMP_TABLE;

-- PRIORITY --------------------------------------------

INSERT INTO TEMP_TABLE SELECT distinct ID_INSTALLATION, PRIORITY, 0 from ALARMLOAD;
UPDATE TEMP_TABLE T, PRIORITY S
SET T.ALREADY_EXISTS=1  
where 
	T.ID_INSTALLATION = S.ID_INSTALLATION 
	and t.NNAME = S.NNAME;

delete from TEMP_TABLE where ALREADY_EXISTS<>0;

INSERT INTO PRIORITY (ID_INSTALLATION, NNAME, DESCRIPTION) SELECT T.ID_INSTALLATION, T.NNAME, ""
	FROM TEMP_TABLE T;

delete from TEMP_TABLE;
    
-- ALARM_STATUS --------------------------------------------

INSERT INTO TEMP_TABLE SELECT distinct ID_INSTALLATION, ALARMSTATUS, 0 from ALARMLOAD;
UPDATE TEMP_TABLE T, ALARMSTATUS S
SET T.ALREADY_EXISTS=1  
where 
	T.ID_INSTALLATION = S.ID_INSTALLATION 
	and t.NNAME = S.NNAME;

delete from TEMP_TABLE where ALREADY_EXISTS<>0;

INSERT INTO ALARMSTATUS (ID_INSTALLATION, NNAME, DESCRIPTION) SELECT T.ID_INSTALLATION, T.NNAME, ""
	FROM TEMP_TABLE T;

delete from TEMP_TABLE;

drop table if exists TEMP_TABLE;

-- ALARM_TYPE --------------------------------------------


UPDATE ALARMLOAD A, SYSTEM S      SET A.ID_SYSTEM    = S.ID   	WHERE A.ID_INSTALLATION = S.ID_INSTALLATION 	and A.SYSTEM    = S.NNAME;
UPDATE ALARMLOAD A, SUBSYSTEM S   SET A.ID_SUBSYSTEM = S.ID   	WHERE A.ID_INSTALLATION = S.ID_INSTALLATION 	and A.SUBSYSTEM = S.NNAME;
UPDATE ALARMLOAD A, MESSAGETYPE S SET A.ID_MESSAGETYPE = S.ID 	WHERE A.ID_INSTALLATION = S.ID_INSTALLATION 	and A.MESSAGETYPE = S.NNAME;
UPDATE ALARMLOAD A, PRIORITY S    SET A.ID_PRIORITY = S.ID    	WHERE A.ID_INSTALLATION = S.ID_INSTALLATION 	and A.PRIORITY = S.NNAME;
UPDATE ALARMLOAD A, ALARMSTATUS S SET A.ID_ALARMSTATUS = S.ID   WHERE A.ID_INSTALLATION = S.ID_INSTALLATION 	and A.ALARMSTATUS = S.NNAME;

UPDATE ALARMLOAD A, ALARMTYPE T 
SET A.ID_ALARMTYPE = T.ID, A.ALREADY_EXISTS = 1
WHERE
    A.ID_INSTALLATION = T.ID_INSTALLATION
        AND A.ID_SYSTEM = T.ID_SYSTEM
        AND A.ID_SUBSYSTEM = T.ID_SUBSYSTEM
        AND A.ID_MESSAGETYPE = T.ID_MESSAGETYPE
        AND A.ID_PRIORITY = T.ID_PRIORITY
        AND A.TAGNAME = T.TAGNAME
        AND A.DESCRIPTION = T.DESCRIPTION;
    
INSERT INTO ALARMTYPE (ID_INSTALLATION, ID_SYSTEM, ID_SUBSYSTEM, ID_MESSAGETYPE, ID_PRIORITY, TAGNAME, DESCRIPTION)
	SELECT  distinct ID_INSTALLATION, ID_SYSTEM, ID_SUBSYSTEM, ID_MESSAGETYPE, ID_PRIORITY, TAGNAME, DESCRIPTION  from ALARMLOAD WHERE ALREADY_EXISTS=0;
    
UPDATE ALARMLOAD A, ALARMTYPE T
SET A.ID_ALARMTYPE = T.ID, A.ALREADY_EXISTS=1  
where 
	A.ID_INSTALLATION = T.ID_INSTALLATION 
	and A.ID_SYSTEM = T.ID_SYSTEM
    and A.ID_SUBSYSTEM = T.ID_SUBSYSTEM
    and A.ID_MESSAGETYPE = T.ID_MESSAGETYPE
    and A.ID_PRIORITY = T.ID_PRIORITY
    and A.TAGNAME = T.TAGNAME
    AND A.DESCRIPTION = T.DESCRIPTION
    AND A.ALREADY_EXISTS=0;

INSERT INTO ALARMDATA (ID_INSTALLATION, ID_FILE, ID_ALARMTYPE, ID_ALARMSTATUS, ALARMTIME)
	SELECT ID_INSTALLATION, ID_FILE, ID_ALARMTYPE, ID_ALARMSTATUS, ALARMTIME FROM ALARMLOAD WHERE ALREADY_EXISTS=1 order by ALARMTIME;

DELETE FROM ALARMLOAD; 


       
          
          
          
      